service: dota2-scrimfinder

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  test:
    handler: src/index.handler
    events:
      - http: 'GET /active_scrims'


plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
