service: dota2-scrimfinder

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  active_scrims:
    handler: src/index.handler
    events:
      - http: 'GET /active_scrims'
  list_scrim:
    handler: src/index.handler
    events:
      - http: 'POST /list_scrim'



plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
